# theme: jekyll-theme-minimal
title: Xin Chen's Personal Region
description: Reference to my academic roadmap.

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# website head image
avatar: https://cx-333.github.io/pics/20201028101019182.png
favicon: https://cx-333.github.io/pics/github_original_wordmark_logo_icon_146506.ico

domain: cx-333.github.io
url: https://cx-333.github.io
# baseurl: 

# personal social
footer-links:
  email: 1354123040@qq.com
  github: https://cx-333.github.io
  zhihu: none
